/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testGhoSol from "./TestGho.sol";
export * as interfaces from "./interfaces";
export * as permit2 from "./permit2";
export { TestERC20__factory } from "./TestERC20__factory";
export { TestERC20Permit__factory } from "./TestERC20Permit__factory";
