/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Permit__factory } from "./ERC20Permit__factory";
export { TestGho__factory } from "./TestGho__factory";
