/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testGhoSol from "./TestGho.sol";
export type { testGhoSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as permit2 from "./permit2";
export type { permit2 };
export type { TestERC20 } from "./TestERC20";
export type { TestERC20Permit } from "./TestERC20Permit";
