/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPBMLogicInterface extends Interface {
  getFunction(
    nameOrSignature: "isBlacklisted" | "isMerchant"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Blacklist" | "MerchantList"): EventFragment;

  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMerchant",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMerchant", data: BytesLike): Result;
}

export namespace BlacklistEvent {
  export type InputTuple = [
    action: string,
    addresses: AddressLike[],
    metadata: string
  ];
  export type OutputTuple = [
    action: string,
    addresses: string[],
    metadata: string
  ];
  export interface OutputObject {
    action: string;
    addresses: string[];
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantListEvent {
  export type InputTuple = [
    action: string,
    addresses: AddressLike[],
    metadata: string
  ];
  export type OutputTuple = [
    action: string,
    addresses: string[],
    metadata: string
  ];
  export interface OutputObject {
    action: string;
    addresses: string[];
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPBMLogic extends BaseContract {
  connect(runner?: ContractRunner | null): IPBMLogic;
  waitForDeployment(): Promise<this>;

  interface: IPBMLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isBlacklisted: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "nonpayable"
  >;

  isMerchant: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "isMerchant"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "nonpayable">;

  getEvent(
    key: "Blacklist"
  ): TypedContractEvent<
    BlacklistEvent.InputTuple,
    BlacklistEvent.OutputTuple,
    BlacklistEvent.OutputObject
  >;
  getEvent(
    key: "MerchantList"
  ): TypedContractEvent<
    MerchantListEvent.InputTuple,
    MerchantListEvent.OutputTuple,
    MerchantListEvent.OutputObject
  >;

  filters: {
    "Blacklist(string,address[],string)": TypedContractEvent<
      BlacklistEvent.InputTuple,
      BlacklistEvent.OutputTuple,
      BlacklistEvent.OutputObject
    >;
    Blacklist: TypedContractEvent<
      BlacklistEvent.InputTuple,
      BlacklistEvent.OutputTuple,
      BlacklistEvent.OutputObject
    >;

    "MerchantList(string,address[],string)": TypedContractEvent<
      MerchantListEvent.InputTuple,
      MerchantListEvent.OutputTuple,
      MerchantListEvent.OutputObject
    >;
    MerchantList: TypedContractEvent<
      MerchantListEvent.InputTuple,
      MerchantListEvent.OutputTuple,
      MerchantListEvent.OutputObject
    >;
  };
}
