/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PBMLogicInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "blacklistAddresses"
      | "isBlacklisted"
      | "isMerchant"
      | "unBlacklistAddresses"
      | "unWhitelistAddresses"
      | "whitelistAddresses"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Blacklist" | "MerchantList"): EventFragment;

  encodeFunctionData(
    functionFragment: "blacklistAddresses",
    values: [AddressLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMerchant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unBlacklistAddresses",
    values: [AddressLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "unWhitelistAddresses",
    values: [AddressLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistAddresses",
    values: [AddressLike[], string]
  ): string;

  decodeFunctionResult(
    functionFragment: "blacklistAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMerchant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unBlacklistAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unWhitelistAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAddresses",
    data: BytesLike
  ): Result;
}

export namespace BlacklistEvent {
  export type InputTuple = [
    action: string,
    addresses: AddressLike[],
    metadata: string
  ];
  export type OutputTuple = [
    action: string,
    addresses: string[],
    metadata: string
  ];
  export interface OutputObject {
    action: string;
    addresses: string[];
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantListEvent {
  export type InputTuple = [
    action: string,
    addresses: AddressLike[],
    metadata: string
  ];
  export type OutputTuple = [
    action: string,
    addresses: string[],
    metadata: string
  ];
  export interface OutputObject {
    action: string;
    addresses: string[];
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PBMLogic extends BaseContract {
  connect(runner?: ContractRunner | null): PBMLogic;
  waitForDeployment(): Promise<this>;

  interface: PBMLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blacklistAddresses: TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;

  isBlacklisted: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  isMerchant: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  unBlacklistAddresses: TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;

  unWhitelistAddresses: TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;

  whitelistAddresses: TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blacklistAddresses"
  ): TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMerchant"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unBlacklistAddresses"
  ): TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unWhitelistAddresses"
  ): TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistAddresses"
  ): TypedContractMethod<
    [_addresses: AddressLike[], metadata: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Blacklist"
  ): TypedContractEvent<
    BlacklistEvent.InputTuple,
    BlacklistEvent.OutputTuple,
    BlacklistEvent.OutputObject
  >;
  getEvent(
    key: "MerchantList"
  ): TypedContractEvent<
    MerchantListEvent.InputTuple,
    MerchantListEvent.OutputTuple,
    MerchantListEvent.OutputObject
  >;

  filters: {
    "Blacklist(string,address[],string)": TypedContractEvent<
      BlacklistEvent.InputTuple,
      BlacklistEvent.OutputTuple,
      BlacklistEvent.OutputObject
    >;
    Blacklist: TypedContractEvent<
      BlacklistEvent.InputTuple,
      BlacklistEvent.OutputTuple,
      BlacklistEvent.OutputObject
    >;

    "MerchantList(string,address[],string)": TypedContractEvent<
      MerchantListEvent.InputTuple,
      MerchantListEvent.OutputTuple,
      MerchantListEvent.OutputObject
    >;
    MerchantList: TypedContractEvent<
      MerchantListEvent.InputTuple,
      MerchantListEvent.OutputTuple,
      MerchantListEvent.OutputObject
    >;
  };
}
