/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ITravelPBMManager {
  export type PBMTokenStruct = {
    name: string;
    faceValue: BigNumberish;
    expiry: BigNumberish;
    uri: string;
    totalSupply: BigNumberish;
    percentSupport: BigNumberish;
  };

  export type PBMTokenStructOutput = [
    name: string,
    faceValue: bigint,
    expiry: bigint,
    uri: string,
    totalSupply: bigint,
    percentSupport: bigint
  ] & {
    name: string;
    faceValue: bigint;
    expiry: bigint;
    uri: string;
    totalSupply: bigint;
    percentSupport: bigint;
  };
}

export interface TravelPBMManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPBMTokenType"
      | "decreaseTotalSupply"
      | "getTokenDetails"
      | "increaseTotalSupply"
      | "owner"
      | "pbmToSov"
      | "renounceOwnership"
      | "setPBM"
      | "sovToPBM"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewPBMTypeCreated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPBMTokenType",
    values: [string, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseTotalSupply",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseTotalSupply",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pbmToSov",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPBM", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "sovToPBM",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPBMTokenType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pbmToSov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPBM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sovToPBM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace NewPBMTypeCreatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    tokenName: string,
    amount: BigNumberish,
    expiry: BigNumberish,
    creator: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    tokenName: string,
    amount: bigint,
    expiry: bigint,
    creator: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    tokenName: string;
    amount: bigint;
    expiry: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TravelPBMManager extends BaseContract {
  connect(runner?: ContractRunner | null): TravelPBMManager;
  waitForDeployment(): Promise<this>;

  interface: TravelPBMManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPBMTokenType: TypedContractMethod<
    [
      _name: string,
      _faceValue: BigNumberish,
      _tokenExpiry: BigNumberish,
      _tokenURI: string,
      _percentSupport: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decreaseTotalSupply: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTokenDetails: TypedContractMethod<
    [tokenId: BigNumberish],
    [ITravelPBMManager.PBMTokenStructOutput],
    "view"
  >;

  increaseTotalSupply: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pbmToSov: TypedContractMethod<
    [tokenId: BigNumberish, pbmAmount: BigNumberish],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPBM: TypedContractMethod<[_pbm: AddressLike], [void], "nonpayable">;

  sovToPBM: TypedContractMethod<
    [tokenId: BigNumberish, sovAmount: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPBMTokenType"
  ): TypedContractMethod<
    [
      _name: string,
      _faceValue: BigNumberish,
      _tokenExpiry: BigNumberish,
      _tokenURI: string,
      _percentSupport: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decreaseTotalSupply"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTokenDetails"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [ITravelPBMManager.PBMTokenStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "increaseTotalSupply"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pbmToSov"
  ): TypedContractMethod<
    [tokenId: BigNumberish, pbmAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPBM"
  ): TypedContractMethod<[_pbm: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sovToPBM"
  ): TypedContractMethod<
    [tokenId: BigNumberish, sovAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NewPBMTypeCreated"
  ): TypedContractEvent<
    NewPBMTypeCreatedEvent.InputTuple,
    NewPBMTypeCreatedEvent.OutputTuple,
    NewPBMTypeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "NewPBMTypeCreated(uint256,string,uint256,uint256,address)": TypedContractEvent<
      NewPBMTypeCreatedEvent.InputTuple,
      NewPBMTypeCreatedEvent.OutputTuple,
      NewPBMTypeCreatedEvent.OutputObject
    >;
    NewPBMTypeCreated: TypedContractEvent<
      NewPBMTypeCreatedEvent.InputTuple,
      NewPBMTypeCreatedEvent.OutputTuple,
      NewPBMTypeCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
